# Generated by Django 2.0.4 on 2018-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_net', models.CharField(choices=[('DKS', 'Дикси'), ('PRKRS', 'Перекресток'), ('VKTR', 'Виктория'), ('BLL', 'BILLA')], max_length=400)),
                ('market_address_ru', models.CharField(max_length=400)),
                ('market_address_en', models.CharField(max_length=400)),
                ('market_lat', models.FloatField()),
                ('market_lng', models.FloatField()),
                ('market_is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='MetroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro_name_ru', models.CharField(max_length=400)),
                ('metro_name_en', models.CharField(max_length=400)),
                ('metro_lat', models.FloatField()),
                ('metro_lng', models.FloatField()),
                ('metro_city', models.CharField(max_length=400)),
                ('metro_is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'MetroStations',
            },
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=400)),
                ('route_status', models.BooleanField()),
                ('route_order', models.CharField(max_length=400)),
                ('route_points', models.ManyToManyField(to='mroute.MarketModel')),
            ],
            options={
                'db_table': 'Routes',
            },
        ),
    ]
