# Generated by Django 2.0.4 on 2018-04-04 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mroute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routemodel',
            old_name='route_order',
            new_name='route_fri_order',
        ),
        migrations.RemoveField(
            model_name='routemodel',
            name='route_points',
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_fri',
            field=models.ManyToManyField(related_name='route_fri', to='mroute.MarketModel'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_fri_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_mon',
            field=models.ManyToManyField(related_name='route_mon', to='mroute.MarketModel'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_mon_order',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_mon_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_sat',
            field=models.ManyToManyField(related_name='route_sat', to='mroute.MarketModel'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_sat_order',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_sat_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_sun',
            field=models.ManyToManyField(related_name='route_sun', to='mroute.MarketModel'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_sun_order',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_sun_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_thu',
            field=models.ManyToManyField(related_name='route_thu', to='mroute.MarketModel'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_thu_order',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_thu_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_tue',
            field=models.ManyToManyField(related_name='route_tue', to='mroute.MarketModel'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_tue_order',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_tue_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_wed',
            field=models.ManyToManyField(related_name='route_wed', to='mroute.MarketModel'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_wed_order',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routemodel',
            name='route_wed_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marketmodel',
            name='market_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='metromodel',
            name='metro_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='route_status',
            field=models.BooleanField(default=True),
        ),
    ]
