# Generated by Django 2.0.4 on 2018-05-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mroute', '0003_auto_20180511_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metromodel',
            name='metro_city',
            field=models.CharField(max_length=400, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='metromodel',
            name='metro_is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='metromodel',
            name='metro_lat',
            field=models.FloatField(verbose_name='Координата X'),
        ),
        migrations.AlterField(
            model_name='metromodel',
            name='metro_lng',
            field=models.FloatField(verbose_name='Координата Y'),
        ),
        migrations.AlterField(
            model_name='metromodel',
            name='metro_name_ru',
            field=models.CharField(max_length=400, verbose_name='Название станции'),
        ),
    ]
