# Generated by Django 2.0.4 on 2018-05-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mroute', '0004_auto_20180511_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='market_net',
            field=models.CharField(choices=[('DKS', 'Дикси'), ('PRKRS', 'Перекресток'), ('VKTR', 'Виктория'), ('BLL', 'BILLA'), ('KRS', 'Карусель'), ('HZ', 'ТД "Холдинг-Центр"')], max_length=400, verbose_name='Сеть'),
        ),
    ]
