# Generated by Django 2.0.4 on 2018-06-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mroute', '0006_auto_20180601_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='market_net',
            field=models.CharField(choices=[('DKS', 'Дикси'), ('PRKRS', 'Перекресток'), ('VKTR', 'Виктория'), ('BLL', 'BILLA'), ('KRS', 'Карусель'), ('HZ', 'ТД "Холдинг-Центр"'), ('MGT', 'Магнит'), ('PTRK', 'Пятерочка')], max_length=400, verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='route_desc',
            field=models.TextField(max_length=500, verbose_name='Описание маршрута'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='route_name',
            field=models.CharField(max_length=400, verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='route_rawArray',
            field=models.TextField(verbose_name='"Сырые" данные маршрута'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='route_status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
