# Generated by Django 2.0.4 on 2018-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mroute', '0007_auto_20180606_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='market_net',
            field=models.CharField(choices=[('DKS', 'Дикси'), ('PRKRS', 'Перекресток'), ('VKTR', 'Виктория'), ('BLL', 'BILLA'), ('KRS', 'Карусель'), ('HZ', 'ТД "Холдинг-Центр"'), ('MGT', 'Магнит'), ('PTRK', 'Пятерочка'), ('LNT', 'Лента')], max_length=400, verbose_name='Сеть'),
        ),
    ]
