# Generated by Django 2.0.4 on 2018-07-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mroute', '0008_auto_20180704_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_code', models.CharField(max_length=100, verbose_name='Код сети (латиница)')),
                ('net_name', models.CharField(max_length=100, verbose_name='Название сети (кирилица)')),
                ('net_status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'db_table': 'Nets',
            },
        ),
    ]
