# Generated by Django 2.0.4 on 2018-07-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mroute', '0009_netmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmodel',
            name='net_icon_link',
            field=models.CharField(default=123, max_length=300, verbose_name='Ссылка на иконку'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netmodel',
            name='net_icon_size',
            field=models.CharField(default=(12, 12), max_length=10, verbose_name='Размеры иконки (через запятую: X, Y)'),
            preserve_default=False,
        ),
    ]
