# Generated by Django 2.0.4 on 2018-07-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mroute', '0012_auto_20180706_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netmodel',
            name='net_icon_size',
        ),
        migrations.AddField(
            model_name='netmodel',
            name='net_icon_size_x',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер иконки по X'),
        ),
        migrations.AddField(
            model_name='netmodel',
            name='net_icon_size_y',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер иконки по Y'),
        ),
    ]
